/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.deth.clientstore.gui;

import com.deth.clientstore.ClientStore;
import com.deth.clientstore.networklayer.TCPClient;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class UserInterface extends javax.swing.JFrame {
    ClientStore clientManager;
    private TCPClient client;

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
        client = new TCPClient("192.168.192.31", 9090);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addProducts = new javax.swing.JButton();
        deleteProducts = new javax.swing.JButton();
        editProducts = new javax.swing.JButton();
        exportInventory = new javax.swing.JButton();
        searchProduct = new javax.swing.JButton();
        searchNameProduct = new javax.swing.JTextField();
        nameProduct = new javax.swing.JTextField();
        priceProduct = new javax.swing.JTextField();
        quantityProduct = new javax.swing.JTextField();
        productDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        closeConnection = new javax.swing.JButton();
        exportLogCsv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User Interface");

        addProducts.setText("add products");
        addProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductsActionPerformed(evt);
            }
        });

        deleteProducts.setText("delete products");
        deleteProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductsActionPerformed(evt);
            }
        });

        editProducts.setText("edit products");
        editProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductsActionPerformed(evt);
            }
        });

        exportInventory.setText("export inventory");
        exportInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportInventoryActionPerformed(evt);
            }
        });

        searchProduct.setText("search products");
        searchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductActionPerformed(evt);
            }
        });

        nameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProductActionPerformed(evt);
            }
        });

        productDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDescriptionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre del producto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Precio del producto");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad del producto");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Descripción del producto");

        closeConnection.setText("salir");
        closeConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeConnectionActionPerformed(evt);
            }
        });

        exportLogCsv.setText("export logs");
        exportLogCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportLogCsvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(priceProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(quantityProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(productDescription))
                            .addComponent(searchNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closeConnection))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(searchProduct)
                            .addComponent(exportInventory))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addProducts)
                            .addComponent(deleteProducts)
                            .addComponent(editProducts)
                            .addComponent(exportLogCsv)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(addProducts))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(deleteProducts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(editProducts)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportLogCsv)
                    .addComponent(exportInventory)
                    .addComponent(closeConnection))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductsActionPerformed
   
        if (nameProduct.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo Nombre del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (priceProduct.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo Precio del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (productDescription.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo Descripción del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (quantityProduct.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El campo Cantidad del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String name = nameProduct.getText();
            float price = Float.parseFloat(priceProduct.getText());
            String description = productDescription.getText();
            int quantity = Integer.parseInt(quantityProduct.getText());

            String message=client.buildMessage("add", name, description, price,quantity);
            JOptionPane.showMessageDialog(null, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error en el formato de los datos. Asegúrate de ingresar un número válido en Precio y Cantidad.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_addProductsActionPerformed

    private void deleteProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductsActionPerformed
        // TODO add your handling code here:
        //eliminar
        if (nameProduct.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debe de especificar el producto a eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);

        }else{
            String name=nameProduct.getText();
            String message=client.buildMessage("delete", name);
            JOptionPane.showMessageDialog(null, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteProductsActionPerformed

    private void editProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductsActionPerformed
        if (nameProduct.getText().isBlank()) {
        JOptionPane.showMessageDialog(null, "El campo Nombre del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (priceProduct.getText().isBlank()) {
        JOptionPane.showMessageDialog(null, "El campo Precio del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (productDescription.getText().isBlank()) {
        JOptionPane.showMessageDialog(null, "El campo Descripción del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (quantityProduct.getText().isBlank()) {
        JOptionPane.showMessageDialog(null, "El campo Cantidad del Producto debe estar lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Manejo de excepciones por tipos de datos incorrectos
    try {
        String name = nameProduct.getText();
        float price = Float.parseFloat(priceProduct.getText());
        String description = productDescription.getText();
        int quantity = Integer.parseInt(quantityProduct.getText());

        // Construcción del mensaje para editar
        String message = client.buildMessage("edit", name, description, price, quantity);
        JOptionPane.showMessageDialog(null, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error en el formato de los datos. Asegúrate de ingresar un número válido en Precio y Cantidad.", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
        
        
        
    }//GEN-LAST:event_editProductsActionPerformed

    private void exportInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportInventoryActionPerformed
        // TODO add your handling code here:
        //para el CSV
        String message=client.buildMessage("exportinventory");
        
        if (message!=null ) {
            if (client.buildCsv(message)) {
                JOptionPane.showMessageDialog(null, "Inventario generado con éxito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }  
        }else{
            JOptionPane.showMessageDialog(null, "ERROR...no hay productos para hacer el inventario", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_exportInventoryActionPerformed

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        // TODO add your handling code here:
        //buscar
    }//GEN-LAST:event_searchProductActionPerformed

    private void nameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProductActionPerformed

    private void productDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productDescriptionActionPerformed

    private void closeConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeConnectionActionPerformed
        // TODO add your handling code here:
        client.closeConnection();
        setVisible(false);
    }//GEN-LAST:event_closeConnectionActionPerformed

    private void exportLogCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportLogCsvActionPerformed
        // TODO add your handling code here:
        String message=client.buildMessage("exportlog");
        JOptionPane.showMessageDialog(null, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_exportLogCsvActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProducts;
    private javax.swing.JButton closeConnection;
    private javax.swing.JButton deleteProducts;
    private javax.swing.JButton editProducts;
    private javax.swing.JButton exportInventory;
    private javax.swing.JButton exportLogCsv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameProduct;
    private javax.swing.JTextField priceProduct;
    private javax.swing.JTextField productDescription;
    private javax.swing.JTextField quantityProduct;
    private javax.swing.JTextField searchNameProduct;
    private javax.swing.JButton searchProduct;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the addProducts
     */
    public javax.swing.JButton getAddProducts() {
        return addProducts;
    }
}
